### ISSUE TITLE
regex support in routef %O

### ISSUE THREAD

**Issue by AngelMunoz** [Lanayx/Oxpecker#26]
Hey there, I've been playing with Oxpecker and so far so good! 

I'm tryng to configure a route with a regex using %O

```fsharp
routef "/posts/{%O:regex(^.+_(\\d{4}-\\d{2}-\\d{2}-\\d+)$)}"
```

However, every time I startup the server I hit this exception

```
Unhandled exception. Microsoft.AspNetCore.Routing.Patterns.RoutePatternException: In a route parameter, '{' and '}' must be escaped with '{{' and '}}'.
   at Microsoft.AspNetCore.Routing.Patterns.RoutePatternParser.Parse(String pattern)
   at Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapMethods(IEndpointRouteBuilder endpoints, String pattern, IEnumerable`1 httpMethods, RequestDelegate requestDelegate)
   at Oxpecker.EndpointRouteBuilderExtensions.MapSingleEndpoint(IEndpointRouteBuilder builder, HttpVerbs verb, String routeTemplate, RequestDelegate requestDelegate, FSharpFunc`2 configure)
   at Oxpecker.EndpointRouteBuilderExtensions.MapOxpeckerEndpoint(IEndpointRouteBuilder builder, Endpoint endpoint)
   at Oxpecker.EndpointRouteBuilderExtensions.MapOxpeckerEndpoints(IEndpointRouteBuilder builder, IEnumerable`1 endpoints)
   at Oxpecker.EndpointRouteBuilderExtensions.MapOxpeckerEndpoint(IEndpointRouteBuilder builder, Endpoint endpoint)
   at Oxpecker.EndpointRouteBuilderExtensions.MapOxpeckerEndpoints(IEndpointRouteBuilder builder, IEnumerable`1 endpoints)
   at Oxpecker.Middleware.UseOxpecker@19.Invoke(IEndpointRouteBuilder builder)
   at Microsoft.AspNetCore.Builder.EndpointRoutingApplicationBuilderExtensions.UseEndpoints(IApplicationBuilder builder, Action`1 configure)
   at Oxpecker.Middleware.ApplicationBuilderExtensions.UseOxpecker(IApplicationBuilder builder, IEnumerable`1 endpoints)
   at <StartupCode$Openapo>.$Program.main@() in X:\Openapo\Program.fs:line 27
```

I'm not sure if I'm missing something or what I'm trying to do is not supported in Oxpecker.

**Comment by Lanayx** [comment]
@AngelMunoz Hi! I think you should do what the error says - replace single curly braces into double curly braces inside regex. Also, it seems you are matching a string, so `%s` should work as well. `%O` is used for types that are not supported by F# routef module, I should probably make it more clear in docs, thanks for raising an issue!

**Comment by AngelMunoz** [comment]
I'm trying to match a string with a particular format hence why I was trying to use a regex definition there. Using `%s` matches only until there's a space or a special character, as an example:

`F# is very good!` gives me `F` as the route parameter 
even if I url encode the string.

Using the double `{{}}` also fails, I digged a bit last night and I think this is likely messing with this regex being used for routef
https://github.com/Lanayx/Oxpecker/blob/develop/src/Oxpecker/Routing.fs#L82

In any case, I'll take that this is not supported currently thanks for the quick answer!

**Comment by Lanayx** [comment]
@AngelMunoz can you please give a regex example that doesn't work for you? I tested this yesterday and it worked:
```fsharp
routef "/posts/{%s:regex(^.+_(\\d{{4}}-\\d{{2}}-\\d{{2}}-\\d+)$)}" (fun id -> text id)
```

**Comment by AngelMunoz** [comment]
Oh right, my bad that one you provided does not have runtime errors at registration but does not match this path for some reason

`/posts/F#%20and%20oxpecker%20are%20doing%20cool%20things!_2024-10-27-38` I get a 404

**Comment by AngelMunoz** [comment]
Here's a quick video of what's going on, a single string matches just fine but the other one does not

https://github.com/user-attachments/assets/4d619aa3-dafb-48cd-8bca-218f22aa00d5

But I'm suspecting that might be due my regex. In any case I am able to use the regex in the path as it was expected. I thought it was just for `%O` but it can be used with `%s` as well. thanks again!
